// Generated by https://quicktype.io

export interface Profile {
    Id: number;
    IdtClena: number;
    Prijmeni: string;
    Jmeno: string;
    Titul: null;
    DatNaroz: null;
    Bydliste: null;
    Emaily: null;
    Telefony: null;
    VekKtg: string;
    VekKtg2: string;
    Senior: boolean;
    Divize: Divize;
    Klub: Klub;
    UserAccess: number;
}

export interface Divize {
    Id: number;
    Nazev: string;
}

export interface Klub {
    Id: number;
    CisDivize: number;
    CisKlubu: number;
    Nazev: string;
    DatVstupu: string;
}
// Generated by https://quicktype.io

export interface CompData {
    VystupujeZa: string;
    Souticence: boolean;
    ProfiSoutLicence: boolean;
    PozastavenaSouticence: boolean;
    ZakazStartu: boolean;
    PlatneZdravProhlidky: PlatneZdravProhlidky[];
    VykDataStt: VykData;
    VykDataLat: VykData;
    VykDataSttSe: null;
    VykDataLatSe: null;
    NejTridaStt: string;
    NejTridaLat: string;
    NejTridaSttSe: null;
    NejTridaLatSe: null;
    ParStt: Par;
    ParLat: Par;
}

export interface Par {
    ParId: number;
    PartnerJmeno: string;
    PartnerPrijmeni: string;
    PartnerIdt: number;
    VekKtg: string;
    VystupujiZa: VystupujiZa;
    VykData: VykData;
    VykDataSe: null;
    SeniorskyPar: boolean;
}

export interface VykData {
    Trida: string;
    Body: number;
    FinTuz: number;
    FinZahr: number;
}

export interface VystupujiZa {
    PartnerVystZa: string;
    PartnerKlubId: number;
    PartnerHostovani: boolean;
    PartnerkaVystZa: string;
    PartnerkaKlubId: number;
    PartnerkaHostovani: boolean;
}

export interface PlatneZdravProhlidky {
    TypId: number;
    Datum: string;
    DoData: string;
    Nazev: string;
}


// Generated by https://quicktype.io

export interface Partner {
    Items: PartnerItem[];
    NextPageLink: null;
    Count: number;
}

export interface PartnerItem {
    Id: number;
    Partner: PartnerClass;
    Partnerka: PartnerClass;
    Stt: Lat;
    Lat: Lat;
    NrtPotvrzParu: null;
    VekKtg: null;
    SeniorskyPar: boolean;
    PartnerEdit: boolean;
    PartnerkaEdit: boolean;
    PotvrditNrt: boolean;
}

export interface Lat {
    Stav: number;
    DatVzniku: null;
    DatUkonceni: null;
    PartnerDatPotvrz: string;
    PartnerkaDatPotvrz: null;
    Trida: string;
    Body: number;
    FinaleTuz: number;
    FinaleZahr: number;
    TridaSe: null;
    BodySe: number;
    FinaleTuzSe: number;
    FinaleZahrSe: number;
    RowVersion: string;
}

export interface PartnerClass {
    Id: number;
    Idt: number;
    Prijmeni: string;
    Jmeno: string;
    KlubId: number;
}

export interface CstsDancerData { profile: Profile, compData: CompData, partner: Partner, compResults: CompResults }

// Generated by https://quicktype.io

export interface CompResults {
    Items: ResultItem[];
    NextPageLink: any;
    Count: number;
}

export interface ResultItem {
    Id: number;
    Datum: string;
    Nazev: string;
    Misto: string;
    Kategorie: string;
    PoradiOd: number;
    PoradiDo: number;
    PartnerIdt: number;
}
