// Generated by https://quicktype.io

export interface WdsfProfile {
  link: Link[];
  id: number;
  name: string;
  surname: string;
  sex: string;
  nationality: string;
  country: string;
  ageGroup: string;
  yearOfBirth: number;
  nationalReference: null;
  licenses: License[];
}

export interface License {
  type: string;
  status: string;
  division: string;
  disciplines: any[];
  expiresOn: string;
}

export interface Link {
  href: string;
  rel: string;
  type?: string;
}



export interface WdsfDancerData {
  profile: WdsfProfile,
  partner: WdsfProfile | undefined
}


export interface WdsfCompetitionGlobal {
  link: Link[];
  id: number;
  name: string;
  lastmodifiedDate: string;
}


export interface WdsfCompetitionDetail {
  link: Link[];
  id: number;
  location: string;
  country: string;
  type: string;
  date: string;
  age: string;
  discipline: string;
  danceform: string;
  division: string;
  status: string;
  coefficient: number;
  lastmodifiedDate: string;
  eventId: number;
  groupId: number;
}
